#define STRINGIFY_(s) #s
#define STRINGIFY(s) STRINGIFY_(s)

#define UVCDYNCTRL_VERSION ${UVCDYNCTRL_VERSION}
#ifndef UVCDYNCTRL_VERSION
	#define UVCDYNCTRL_VERSION 0.0
#endif
#define VERSION STRINGIFY(UVCDYNCTRL_VERSION)

#define UVCDYNCTRL_DATA_DIR ${UVCDYNCTRL_DATA_DIR}/data
#ifndef UVCDYNCTRL_DATA_DIR
	#define UVCDYNCTRL_DATA_DIR /usr/share/uvcdynctrl/data
#endif
#define DATA_DIR STRINGIFY(UVCDYNCTRL_DATA_DIR)
